language: go
services:
  - mysql

env:
  - MYSQL_TEST="true"

go:
  - 1.8.4
  - 1.9.1
  - tip

matrix:
  allow_failures:
    - go: tip

before_install:
  - go get -v github.com/golang/lint/golint

install:
  - go version

before_script:
  - mysql < db/seed.sql

sudo: false
script:
  - ./run_tests.sh
